import { createFileRoute } from "@tanstack/react-router";
import { ActionLink, PageHero, SiteFooter, SiteHeader } from "../components/site-chrome";
import { CardGrid, Section, SectionHead } from "../components/page-parts";
import { useLanguage } from "../lib/language";
import jewelleryImage from "../assets/priya-jewellery.jpg";
import heroImage from "../assets/priya-bridal-hero.jpg";

export const Route = createFileRoute("/cultural-looks")({ component: CulturalLooksPage, head: () => ({ meta: [
  { title: "Indian Cultural & Kannada Bridal Looks | Priya Makeover" }, { name: "description", content: "Kannada, South Indian, North Indian and festive makeup, hair, draping and ornament styling." },
  { property: "og:title", content: "Cultural bridal looks by Priya Makeover" }, { property: "og:description", content: "Tradition-aware bridal styling for Kannada and Indian wedding ceremonies." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }) });

function CulturalLooksPage() { const { pick } = useLanguage(); const looks = pick([
  { meta: "Karnataka", title: "Kannada bridal", text: "Muhurtham styling shaped around silk, temple jewellery, flowers and family customs.", points: ["Kanjeevaram drape", "Jasmine braid or bun", "Kumkum and bindi details"] },
  { meta: "Kodagu", title: "Coorg bridal", text: "The distinctive Kodava saree drape and restrained beauty finish, handled with cultural care.", points: ["Back-to-front drape", "Traditional head detail", "Natural polished makeup"] },
  { meta: "South India", title: "Temple wedding", text: "Gold-warm makeup, defined eyes and hair designed to carry layered temple ornaments.", points: ["Kasu and Lakshmi layers", "Jada ornament placement", "Ceremony-proof setting"] },
  { meta: "North India", title: "Lehenga bridal", text: "Balanced glamour for richly embroidered lehengas, double dupattas and kundan jewellery.", points: ["Kundan colour balance", "Double-dupatta setting", "HD or airbrush finish"] },
  { meta: "Celebrations", title: "Festive & pooja", text: "Elegant styling for festivals, naming ceremonies, baby showers and family milestones.", points: ["Soft glam makeup", "Saree draping", "Fresh flower styling"] },
  { meta: "Together", title: "Family styling", text: "Coordinated makeup, hair and draping for mothers, sisters and bridesmaids without making everyone identical.", points: ["Shared timeline", "Age-aware makeup", "Coordinated colour story"] },
], [
  { meta: "ಕರ್ನಾಟಕ", title: "ಕನ್ನಡ ವಧು", text: "ರೇಷ್ಮೆ, ಟೆಂಪಲ್ ಆಭರಣ, ಹೂವು ಮತ್ತು ಕುಟುಂಬದ ಸಂಪ್ರದಾಯಕ್ಕೆ ತಕ್ಕ ಮುಹೂರ್ತದ ಸ್ಟೈಲಿಂಗ್.", points: ["ಕಾಂಜೀವರಂ ಡ್ರೇಪ್", "ಮಲ್ಲಿಗೆ ಜಡೆ ಅಥವಾ ಬನ್", "ಕುಂಕುಮ ಮತ್ತು ಬಿಂದಿ ವಿವರ"] },
  { meta: "ಕೊಡಗು", title: "ಕೊಡವ ವಧು", text: "ವಿಶಿಷ್ಟ ಕೊಡವ ಸೀರೆ ಡ್ರೇಪ್ ಮತ್ತು ಸರಳ ಸೌಂದರ್ಯದ ಫಿನಿಷ್ ಅನ್ನು ಸಂಸ್ಕೃತಿಗೆ ಗೌರವದಿಂದ ಮಾಡಲಾಗುತ್ತದೆ.", points: ["ಹಿಂದಿನಿಂದ ಮುಂದಿನ ಡ್ರೇಪ್", "ಸಾಂಪ್ರದಾಯಿಕ ತಲೆ ಅಲಂಕಾರ", "ಸಹಜ ಮೇಕಪ್"] },
  { meta: "ದಕ್ಷಿಣ ಭಾರತ", title: "ದೇವಸ್ಥಾನ ಮದುವೆ", text: "ಲೇಯರ್ ಟೆಂಪಲ್ ಆಭರಣಗಳಿಗೆ ಹೊಂದುವ ಗೋಲ್ಡನ್ ಮೇಕಪ್, ಸ್ಪಷ್ಟ ಕಣ್ಣು ಮತ್ತು ಹೇರ್.", points: ["ಕಾಸು ಮತ್ತು ಲಕ್ಷ್ಮಿ ಹಾರ", "ಜಡೆ ಆಭರಣ ಅಳವಡಿಕೆ", "ಶಾಸ್ತ್ರಕ್ಕೆ ತಕ್ಕ ಸೆಟ್ಟಿಂಗ್"] },
  { meta: "ಉತ್ತರ ಭಾರತ", title: "ಲೆಹೆಂಗಾ ವಧು", text: "ಭಾರೀ ಲೆಹೆಂಗಾ, ಡಬಲ್ ದುಪಟ್ಟಾ ಮತ್ತು ಕುಂದನ್ ಆಭರಣಕ್ಕೆ ಸಮತೋಲನದ ಗ್ಲಾಮರ್.", points: ["ಕುಂದನ್ ಬಣ್ಣ ಹೊಂದಾಣಿಕೆ", "ಡಬಲ್ ದುಪಟ್ಟಾ ಸೆಟ್ಟಿಂಗ್", "HD ಅಥವಾ ಏರ್‌ಬ್ರಶ್ ಫಿನಿಷ್"] },
  { meta: "ಸಂಭ್ರಮ", title: "ಹಬ್ಬ ಮತ್ತು ಪೂಜೆ", text: "ಹಬ್ಬ, ನಾಮಕರಣ, ಸೀಮಂತ ಮತ್ತು ಕುಟುಂಬ ಸಮಾರಂಭಗಳಿಗೆ ಸೊಗಸಾದ ಸ್ಟೈಲಿಂಗ್.", points: ["ಸಾಫ್ಟ್ ಗ್ಲಾಮ್", "ಸೀರೆ ಡ್ರೇಪಿಂಗ್", "ತಾಜಾ ಹೂವಿನ ಅಲಂಕಾರ"] },
  { meta: "ಒಟ್ಟಿಗೆ", title: "ಕುಟುಂಬದ ಸ್ಟೈಲಿಂಗ್", text: "ತಾಯಿ, ಸಹೋದರಿ ಮತ್ತು ವಧುವಿನ ಸ್ನೇಹಿತರಿಗೆ ಅವರವರ ವೈಶಿಷ್ಟ್ಯ ಉಳಿಸುವ ಹೊಂದಾಣಿಕೆಯ ಮೇಕಪ್ ಮತ್ತು ಹೇರ್.", points: ["ಒಟ್ಟಿನ ಟೈಮ್‌ಲೈನ್", "ವಯಸ್ಸಿಗೆ ತಕ್ಕ ಮೇಕಪ್", "ಹೊಂದಾಣಿಕೆಯ ಬಣ್ಣದ ಕಥೆ"] },
]); return <main className="min-h-screen bg-background text-foreground"><SiteHeader overlay /><PageHero eyebrow={pick("Culture, carried beautifully", "ಸಂಸ್ಕೃತಿಯ ಸುಂದರ ಅಭಿವ್ಯಕ್ತಿ")} title={pick(<>Tradition in every <em>considered detail.</em></>, <>ಪ್ರತಿಯೊಂದು ವಿವರದಲ್ಲೂ <em>ಸಂಪ್ರದಾಯ.</em></>)} intro={pick("Regional beauty is never treated like a costume. We listen to your family, understand the ritual and style each detail with respect.", "ಪ್ರಾದೇಶಿಕ ಸೌಂದರ್ಯ ವೇಷವಲ್ಲ. ನಿಮ್ಮ ಕುಟುಂಬದ ಮಾತು ಕೇಳಿ, ಶಾಸ್ತ್ರ ತಿಳಿದು, ಪ್ರತಿಯೊಂದು ವಿವರವನ್ನು ಗೌರವದಿಂದ ರೂಪಿಸುತ್ತೇವೆ.")} image={heroImage} alt={pick("Traditional Indian bridal styling", "ಸಾಂಪ್ರದಾಯಿಕ ಭಾರತೀಯ ವಧು ಸ್ಟೈಲಿಂಗ್")} /><Section><SectionHead eyebrow={pick("Regional artistry", "ಪ್ರಾದೇಶಿಕ ಸೌಂದರ್ಯ ಕಲೆ")} title={pick(<>Rooted in ritual, <em>personal to you.</em></>, <>ಸಂಪ್ರದಾಯದಲ್ಲಿ ಬೇರೂರಿ, <em>ನಿಮಗಾಗಿ ರೂಪಿಸಿದ.</em></>)} /><CardGrid items={looks} /></Section><Section tone="terracotta"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div className="image-frame group aspect-[4/5]"><img src={jewelleryImage} alt={pick("Traditional bridal jewellery", "ಸಾಂಪ್ರದಾಯಿಕ ವಧು ಆಭರಣ")} className="gallery-image" loading="lazy" /></div><div><SectionHead eyebrow={pick("Family consultation", "ಕುಟುಂಬದ ಸಮಾಲೋಚನೆ")} muted title={pick(<>Your customs lead <em>the plan.</em></>, <>ನಿಮ್ಮ ಸಂಪ್ರದಾಯವೇ <em>ಯೋಜನೆಗೆ ದಾರಿ.</em></>)} intro={pick("Share reference photographs, heirloom jewellery and any family-specific customs. We create a clear plan for drape, flowers, ornaments, bindi and timing before the ceremony.", "ಕುಟುಂಬದ ಹಳೆಯ ಚಿತ್ರಗಳು, ಪಾರಂಪರಿಕ ಆಭರಣ ಮತ್ತು ವಿಶೇಷ ಸಂಪ್ರದಾಯಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಿ. ಶಾಸ್ತ್ರಕ್ಕೂ ಮುನ್ನ ಡ್ರೇಪ್, ಹೂವು, ಆಭರಣ, ಬಿಂದಿ ಮತ್ತು ಸಮಯದ ಸ್ಪಷ್ಟ ಯೋಜನೆ ಮಾಡುತ್ತೇವೆ.")} /><div className="mt-10"><ActionLink to="/contact" light>{pick("Discuss your ceremony", "ನಿಮ್ಮ ಶಾಸ್ತ್ರದ ಬಗ್ಗೆ ಮಾತನಾಡಿ")}</ActionLink></div></div></div></Section><SiteFooter /></main>; }
