import { createFileRoute } from "@tanstack/react-router";
import { ActionLink, PageHero, SiteFooter, SiteHeader } from "../components/site-chrome";
import { CardGrid, DetailList, Section, SectionHead } from "../components/page-parts";
import { useLanguage } from "../lib/language";
import dressesImage from "../assets/priya-dresses.jpg";
import jewelleryImage from "../assets/priya-jewellery.jpg";

export const Route = createFileRoute("/rental-guide")({ component: RentalGuidePage, head: () => ({ meta: [
  { title: "Dress & Jewellery Rental Guide | Priya Makeover" }, { name: "description", content: "How Priya Makeover dress, jewellery and ornament rentals work, including fittings, deposits, care and returns." },
  { property: "og:title", content: "Priya Makeover rental guide" }, { property: "og:description", content: "A clear guide to selecting, fitting, collecting and returning bridal rental pieces." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }) });

function RentalGuidePage() { const { pick } = useLanguage(); const steps = pick([
  { meta: "Step 01", title: "Shortlist", text: "Share your ceremony, size, colour palette and budget before visiting so the right pieces are ready." },
  { meta: "Step 02", title: "Try & coordinate", text: "Try the outfit and jewellery together under studio light; photograph the full combination." },
  { meta: "Step 03", title: "Fit & reserve", text: "Minor alterations are pinned, the deposit is recorded and your pieces are reserved for the date." },
  { meta: "Step 04", title: "Collect", text: "Collect one day before the function after a final item-by-item condition check." },
  { meta: "Step 05", title: "Wear with confidence", text: "The studio can drape, place jewellery and secure ornaments on the day." },
  { meta: "Step 06", title: "Return", text: "Return on the agreed date. After inspection, the refundable deposit is released." },
], [
  { meta: "ಹಂತ 01", title: "ಆಯ್ಕೆಪಟ್ಟಿ", text: "ಭೇಟಿಗೆ ಮುನ್ನ ಸಮಾರಂಭ, ಅಳತೆ, ಬಣ್ಣ ಮತ್ತು ಬಜೆಟ್ ತಿಳಿಸಿ; ಸರಿಯಾದ ಆಯ್ಕೆಗಳನ್ನು ಸಿದ್ಧಪಡಿಸುತ್ತೇವೆ." },
  { meta: "ಹಂತ 02", title: "ಟ್ರಯಲ್ ಮತ್ತು ಹೊಂದಾಣಿಕೆ", text: "ಸ್ಟುಡಿಯೋ ಬೆಳಕಿನಲ್ಲಿ ಉಡುಪು ಮತ್ತು ಆಭರಣ ಒಟ್ಟಿಗೆ ಪ್ರಯತ್ನಿಸಿ; ಪೂರ್ಣ ಕಾಂಬಿನೇಷನ್‌ನ ಚಿತ್ರ ತೆಗೆದುಕೊಳ್ಳಿ." },
  { meta: "ಹಂತ 03", title: "ಫಿಟ್ ಮತ್ತು ಕಾಯ್ದಿರಿಸಿ", text: "ಸಣ್ಣ ಬದಲಾವಣೆ ಗುರುತಿಸಿ, ಠೇವಣಿ ದಾಖಲಿಸಿ, ನಿಮ್ಮ ದಿನಾಂಕಕ್ಕೆ ವಸ್ತುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗುತ್ತದೆ." },
  { meta: "ಹಂತ 04", title: "ಪಡೆಯಿರಿ", text: "ಕಾರ್ಯಕ್ರಮದ ಒಂದು ದಿನ ಮೊದಲು ಅಂತಿಮ ಸ್ಥಿತಿ ಪರಿಶೀಲನೆಯ ನಂತರ ಪಡೆಯಿರಿ." },
  { meta: "ಹಂತ 05", title: "ಆತ್ಮವಿಶ್ವಾಸದಿಂದ ಧರಿಸಿ", text: "ಕಾರ್ಯಕ್ರಮದ ದಿನ ಸ್ಟುಡಿಯೋ ಡ್ರೇಪ್, ಆಭರಣ ಮತ್ತು ಅಲಂಕಾರವನ್ನು ಭದ್ರವಾಗಿ ಅಳವಡಿಸಬಹುದು." },
  { meta: "ಹಂತ 06", title: "ಹಿಂತಿರುಗಿಸಿ", text: "ಒಪ್ಪಿದ ದಿನ ಹಿಂತಿರುಗಿಸಿ. ಪರಿಶೀಲನೆಯ ನಂತರ ಮರುಪಾವತಿ ಠೇವಣಿ ಬಿಡುಗಡೆ ಮಾಡಲಾಗುತ್ತದೆ." },
]); const terms = pick([
  { term: "Rental window", detail: "The standard window is three days: collection, event day and return. Extra days need prior approval." }, { term: "Security deposit", detail: "A refundable deposit depends on the value of each piece and is written on the rental receipt." }, { term: "Alterations", detail: "Only reversible studio alterations are allowed. Do not cut, glue, stitch or pin pieces yourself." }, { term: "Cleaning", detail: "Normal professional cleaning is included. Do not wash, iron, spray perfume or apply makeup directly near the garment." }, { term: "Damage or loss", detail: "Normal wear is accepted. Repairable damage is charged at cost; major damage or loss may use part or all of the deposit." }, { term: "Jewellery care", detail: "Keep jewellery dry, return every detachable piece in its labelled box, and report loose stones immediately." },
], [
  { term: "ಬಾಡಿಗೆ ಅವಧಿ", detail: "ಸಾಮಾನ್ಯ ಅವಧಿ ಮೂರು ದಿನ: ಪಡೆಯುವ ದಿನ, ಕಾರ್ಯಕ್ರಮದ ದಿನ ಮತ್ತು ಹಿಂತಿರುಗಿಸುವ ದಿನ. ಹೆಚ್ಚುವರಿ ದಿನಗಳಿಗೆ ಪೂರ್ವ ಅನುಮತಿ ಬೇಕು." }, { term: "ಭದ್ರತಾ ಠೇವಣಿ", detail: "ಪ್ರತಿ ವಸ್ತುವಿನ ಮೌಲ್ಯಕ್ಕೆ ಅನುಗುಣವಾದ ಮರುಪಾವತಿ ಠೇವಣಿಯನ್ನು ರಸೀದಿಯಲ್ಲಿ ಬರೆಯಲಾಗುತ್ತದೆ." }, { term: "ಬದಲಾವಣೆ", detail: "ಹಿಂದಕ್ಕೆ ಸರಿಪಡಿಸಬಹುದಾದ ಸ್ಟುಡಿಯೋ ಬದಲಾವಣೆ ಮಾತ್ರ ಅನುಮತಿಸಲಾಗಿದೆ. ನೀವೇ ಕತ್ತರಿಸಬೇಡಿ, ಅಂಟಿಸಬೇಡಿ ಅಥವಾ ಹೊಲಿಯಬೇಡಿ." }, { term: "ಸ್ವಚ್ಛತೆ", detail: "ಸಾಮಾನ್ಯ ವೃತ್ತಿಪರ ಸ್ವಚ್ಛತೆ ಒಳಗೊಂಡಿದೆ. ಉಡುಪನ್ನು ತೊಳೆಯಬೇಡಿ, ಇಸ್ತ್ರಿ ಮಾಡಬೇಡಿ ಅಥವಾ ಪರ್ಫ್ಯೂಮ್ ಸಿಂಪಡಿಸಬೇಡಿ." }, { term: "ಹಾನಿ ಅಥವಾ ನಷ್ಟ", detail: "ಸಾಮಾನ್ಯ ಬಳಕೆಯ ಗುರುತು ಸ್ವೀಕಾರಾರ್ಹ. ದುರಸ್ತಿ ವೆಚ್ಚ ಅಥವಾ ದೊಡ್ಡ ಹಾನಿ/ನಷ್ಟವನ್ನು ಠೇವಣಿಯಿಂದ ಕಡಿತ ಮಾಡಬಹುದು." }, { term: "ಆಭರಣದ ಕಾಳಜಿ", detail: "ಆಭರಣ ಒಣವಾಗಿರಲಿ, ಪ್ರತಿಯೊಂದು ಭಾಗವನ್ನು ಗುರುತು ಹಾಕಿದ ಪೆಟ್ಟಿಗೆಯಲ್ಲಿ ಹಿಂತಿರುಗಿಸಿ, ಸಡಿಲ ಕಲ್ಲನ್ನು ತಕ್ಷಣ ತಿಳಿಸಿ." },
]); return <main className="min-h-screen bg-background text-foreground"><SiteHeader overlay /><PageHero eyebrow={pick("Rental guide", "ಬಾಡಿಗೆ ಮಾರ್ಗದರ್ಶಿ")} title={pick(<>Borrow beautifully, <em>return simply.</em></>, <>ಸುಂದರವಾಗಿ ಧರಿಸಿ, <em>ಸರಳವಾಗಿ ಹಿಂತಿರುಗಿಸಿ.</em></>)} intro={pick("Everything you need to know about selecting, fitting, collecting and caring for rental outfits, jewellery and ornaments.", "ಬಾಡಿಗೆ ಉಡುಪು, ಆಭರಣ ಮತ್ತು ಅಲಂಕಾರವನ್ನು ಆಯ್ಕೆ, ಫಿಟ್, ಪಡೆಯುವಿಕೆ ಮತ್ತು ಕಾಳಜಿಯ ಬಗ್ಗೆ ಬೇಕಾದ ಎಲ್ಲ ಮಾಹಿತಿ.")} image={dressesImage} alt={pick("Rental dresses in the studio", "ಸ್ಟುಡಿಯೋದಲ್ಲಿರುವ ಬಾಡಿಗೆ ಉಡುಪುಗಳು")} /><Section><SectionHead eyebrow={pick("The complete process", "ಪೂರ್ಣ ಪ್ರಕ್ರಿಯೆ")} title={pick(<>Six clear steps, <em>no surprises.</em></>, <>ಆರು ಸರಳ ಹಂತಗಳು, <em>ಯಾವುದೇ ಗೊಂದಲವಿಲ್ಲ.</em></>)} /><CardGrid items={steps} /></Section><Section tone="sage"><div className="grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:gap-20"><div><SectionHead eyebrow={pick("Terms & care", "ನಿಯಮ ಮತ್ತು ಕಾಳಜಿ")} title={pick(<>Know before you <em>reserve.</em></>, <>ಕಾಯ್ದಿರಿಸುವ ಮುನ್ನ <em>ತಿಳಿಯಿರಿ.</em></>)} /><DetailList items={terms} /></div><div className="image-frame group aspect-[4/5]"><img src={jewelleryImage} alt={pick("Rental jewellery set", "ಬಾಡಿಗೆ ಆಭರಣ ಸೆಟ್")} className="gallery-image" loading="lazy" /></div></div></Section><Section tone="forest"><SectionHead eyebrow={pick("Ready to shortlist?", "ಆಯ್ಕೆ ಮಾಡಲು ಸಿದ್ಧವೇ?")} muted title={pick(<>Bring your outfit story, <em>we’ll build the rest.</em></>, <>ನಿಮ್ಮ ಉಡುಪಿನ ಕಲ್ಪನೆ ತನ್ನಿ, <em>ಉಳಿದುದನ್ನು ನಾವು ರೂಪಿಸುತ್ತೇವೆ.</em></>)} /><div className="mt-10 flex flex-wrap gap-8"><ActionLink to="/rentals" light>{pick("Browse dress categories", "ಉಡುಪು ವಿಭಾಗಗಳನ್ನು ನೋಡಿ")}</ActionLink><ActionLink to="/contact" light>{pick("Book a fitting", "ಫಿಟಿಂಗ್ ಬುಕ್ ಮಾಡಿ")}</ActionLink></div></Section><SiteFooter /></main>; }