/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BridalMakeupRouteImport } from './routes/bridal-makeup'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CulturalLooksRouteImport } from './routes/cultural-looks'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HairDrapingRouteImport } from './routes/hair-draping'
import { Route as LocationRouteImport } from './routes/location'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as OrnamentsRouteImport } from './routes/ornaments'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RentalGuideRouteImport } from './routes/rental-guide'
import { Route as RentalsRouteImport } from './routes/rentals'
import { Route as ServicesRouteImport } from './routes/services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BridalMakeupRoute = BridalMakeupRouteImport.update({
  id: '/bridal-makeup',
  path: '/bridal-makeup',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CulturalLooksRoute = CulturalLooksRouteImport.update({
  id: '/cultural-looks',
  path: '/cultural-looks',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HairDrapingRoute = HairDrapingRouteImport.update({
  id: '/hair-draping',
  path: '/hair-draping',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const OrnamentsRoute = OrnamentsRouteImport.update({
  id: '/ornaments',
  path: '/ornaments',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalGuideRoute = RentalGuideRouteImport.update({
  id: '/rental-guide',
  path: '/rental-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsRoute = RentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bridal-makeup': typeof BridalMakeupRoute
  '/contact': typeof ContactRoute
  '/cultural-looks': typeof CulturalLooksRoute
  '/faq': typeof FaqRoute
  '/hair-draping': typeof HairDrapingRoute
  '/location': typeof LocationRoute
  '/lookbook': typeof LookbookRoute
  '/ornaments': typeof OrnamentsRoute
  '/pricing': typeof PricingRoute
  '/rental-guide': typeof RentalGuideRoute
  '/rentals': typeof RentalsRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bridal-makeup': typeof BridalMakeupRoute
  '/contact': typeof ContactRoute
  '/cultural-looks': typeof CulturalLooksRoute
  '/faq': typeof FaqRoute
  '/hair-draping': typeof HairDrapingRoute
  '/location': typeof LocationRoute
  '/lookbook': typeof LookbookRoute
  '/ornaments': typeof OrnamentsRoute
  '/pricing': typeof PricingRoute
  '/rental-guide': typeof RentalGuideRoute
  '/rentals': typeof RentalsRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bridal-makeup': typeof BridalMakeupRoute
  '/contact': typeof ContactRoute
  '/cultural-looks': typeof CulturalLooksRoute
  '/faq': typeof FaqRoute
  '/hair-draping': typeof HairDrapingRoute
  '/location': typeof LocationRoute
  '/lookbook': typeof LookbookRoute
  '/ornaments': typeof OrnamentsRoute
  '/pricing': typeof PricingRoute
  '/rental-guide': typeof RentalGuideRoute
  '/rentals': typeof RentalsRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bridal-makeup'
    | '/contact'
    | '/cultural-looks'
    | '/faq'
    | '/hair-draping'
    | '/location'
    | '/lookbook'
    | '/ornaments'
    | '/pricing'
    | '/rental-guide'
    | '/rentals'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bridal-makeup'
    | '/contact'
    | '/cultural-looks'
    | '/faq'
    | '/hair-draping'
    | '/location'
    | '/lookbook'
    | '/ornaments'
    | '/pricing'
    | '/rental-guide'
    | '/rentals'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bridal-makeup'
    | '/contact'
    | '/cultural-looks'
    | '/faq'
    | '/hair-draping'
    | '/location'
    | '/lookbook'
    | '/ornaments'
    | '/pricing'
    | '/rental-guide'
    | '/rentals'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BridalMakeupRoute: typeof BridalMakeupRoute
  ContactRoute: typeof ContactRoute
  CulturalLooksRoute: typeof CulturalLooksRoute
  FaqRoute: typeof FaqRoute
  HairDrapingRoute: typeof HairDrapingRoute
  LocationRoute: typeof LocationRoute
  LookbookRoute: typeof LookbookRoute
  OrnamentsRoute: typeof OrnamentsRoute
  PricingRoute: typeof PricingRoute
  RentalGuideRoute: typeof RentalGuideRoute
  RentalsRoute: typeof RentalsRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridal-makeup': {
      id: '/bridal-makeup'
      path: '/bridal-makeup'
      fullPath: '/bridal-makeup'
      preLoaderRoute: typeof BridalMakeupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cultural-looks': {
      id: '/cultural-looks'
      path: '/cultural-looks'
      fullPath: '/cultural-looks'
      preLoaderRoute: typeof CulturalLooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hair-draping': {
      id: '/hair-draping'
      path: '/hair-draping'
      fullPath: '/hair-draping'
      preLoaderRoute: typeof HairDrapingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ornaments': {
      id: '/ornaments'
      path: '/ornaments'
      fullPath: '/ornaments'
      preLoaderRoute: typeof OrnamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental-guide': {
      id: '/rental-guide'
      path: '/rental-guide'
      fullPath: '/rental-guide'
      preLoaderRoute: typeof RentalGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals': {
      id: '/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof RentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BridalMakeupRoute: BridalMakeupRoute,
  ContactRoute: ContactRoute,
  CulturalLooksRoute: CulturalLooksRoute,
  FaqRoute: FaqRoute,
  HairDrapingRoute: HairDrapingRoute,
  LocationRoute: LocationRoute,
  LookbookRoute: LookbookRoute,
  OrnamentsRoute: OrnamentsRoute,
  PricingRoute: PricingRoute,
  RentalGuideRoute: RentalGuideRoute,
  RentalsRoute: RentalsRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
